App\Entity\Locale:
    type: entity
    repositoryClass: App\Repository\LocaleRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 2
