App\Entity\Question:
    type: entity
    repositoryClass: App\Repository\QuestionRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 150
        code:
            type: string
            length: 255
            nullable: true
    manyToMany:
        answers:
            targetEntity: Answer
            joinTable:
                name: question_answer
                joinColumns:
                    question_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    answer_id:
                        referencedColumnName: id
