version: '3'

services:
    app:
        build:
            context: ./docker/app/
            dockerfile: ./Dockerfile
        environment:
            - COMPOSER_CACHE_DIR=/tmp
            - COMPOSER_PROCESS_TIMEOUT=600
            - HOME=/tmp
        volumes:
            - ./:/app
            - ./vendor:/app/vendor:delegated
            - ./var:/app/var:delegated
            - composer:/tmp/.composer
    node:
        image: node:12-alpine
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            - HOME=/tmp
        stdin_open: true
        tty: false

    database:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root

    server:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/app/public:ro
        ports:
            - 80:80
        depends_on: [app]

volumes:
  composer: {}
